version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: hf_web
    volumes:
      - .:/HF
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=human_firewall
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="welcome@hf"

volumes:
  db_volume: