# Generated by Django 3.1.2 on 2020-12-03 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campId', models.AutoField(primary_key=True, serialize=False)),
                ('campaignName', models.CharField(max_length=50)),
                ('emailTemplate', models.IntegerField()),
                ('landingPage', models.IntegerField()),
                ('sendingProfile', models.IntegerField()),
                ('group', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=50, unique=True)),
                ('totalUsers', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(through='App.GroupedUsers', to='App.Targets')),
            ],
        ),
        migrations.CreateModel(
            name='SendingProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('_from', models.EmailField(db_column='from', max_length=100)),
                ('host', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=512)),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupedusers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usergroups'),
        ),
        migrations.AddField(
            model_name='groupedusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.targets'),
        ),
        migrations.CreateModel(
            name='EmailTemp',
            fields=[
                ('tempId', models.AutoField(primary_key=True, serialize=False)),
                ('tempName', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('text_html', models.TextField()),
                ('userId', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userClickStatus', models.BooleanField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.targets')),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(through='App.CampaignResults', to='App.Targets'),
        ),
        migrations.AlterUniqueTogether(
            name='groupedusers',
            unique_together={('user', 'group')},
        ),
    ]
