# Generated by Django 3.1.1 on 2020-11-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemp',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemp',
            name='tempName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='targets',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='targets',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='targets',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='targets',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usergroups',
            name='groupName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
