# Generated by Django 3.1.2 on 2020-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20201210_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaignStatus',
            field=models.CharField(default='Created', max_length=50),
        ),
    ]
