# Generated by Django 3.1.2 on 2020-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_campaign_campaignstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='totalCredsCaptured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='totalEmailOpened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='totalLinkOpened',
            field=models.IntegerField(default=0),
        ),
    ]
